name: working_wirh_asset_in_flutter_and_the_pubspec_file
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.1 <3.0.0"
# pubspec.yaml파일에서는 // 대신에 #을 주석으로 쓴다.
# pubspec.yaml파일은 들여쓰기가 중요하다.
# pubsepc.yaml은 들여쓰기가 child 역할을 한다.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # 이미지를 추가하는 부분이다.
  # images폴더를 프로젝트 폴더 안에 생성하고 이미지 파일을 넣으면 된다.
  # 이미지가 많으면 폴더를 지정해서 이미지를 등록할 수 있다.
  # 이미지 등록을 마치면 Package get으로 등록한 내용을 확인해준다.
  assets:
    - images/youngcheol.jpg
  